---
title: 'Homework #10'
author: "Sang Doan"
date: "11/8/2020"
output: pdf_document
---

```{r setup, include = FALSE}
source('config.R')
```
# Problem 1
An `Email` object contains the sender's and the recipient's names and the full file path.
```{r warning = FALSE}
'../raw_data/enron_dataset/arnold-j/sent/35.' %>%
  Email
```

# Problem 2
```{r warning = FALSE}
Cuilla <- Employee('cuilla-m')
get_name.Employee(Cuilla)
get_number_of_emails.Employee(Cuilla)
get_email_filename.Employee(Cuilla, 8)
```

# Problem 3
Functions starting with `map` are from package `purrr`. They are generally faster than the `base::apply` family. 
```{r warning = FALSE}
Emails <- c('jones-t', 'shackleton-s', 'sager-e', 'taylor-m', 'stclair-c') %>%
  map(function(.thisE) Employee(.thisE))

names <- map_chr(1:5, function(x) Emails[[x]]$name) %>%
  print

mat <- sapply(1:5, function(x) {
  
  dat <- setDT(Emails[[x]]$emails) %>% 
    transpose
  
  count <- map_int(1:5, function(x) dat[V2 == names[x], length(V2)])
  
  return(count)
}) %>%
  print

gra <- graph_from_adjacency_matrix(mat, mode = 'directed', weighted = TRUE, diag = FALSE)
plot(
  gra,
  vertex.size = 0,
  vertex.label = names,
  edge.label = edge_attr(gra)$weight
)
```

# Code
## `config.R`
```{r echo = TRUE, eval = FALSE}
source('analysis.R')

library(tidyverse)
library(magrittr)
library(data.table)
library(igraph)
```

## `analysis.R`
```{r echo = TRUE, eval = FALSE}
# Problem 1
Email <- function(filename) {
  email <- readLines(filename)
  out <- email[which(str_detect(email, 'X-From: |X-To: '))] %>% str_remove('X-From: |X-To: ') 
  out[3] <- filename
  
  return(out) #Vector out: [1] sender, [2] recipient, [3] full path
}

from.Email <- function(em) em[1]
to.Email <- function(em) em[2]

# Problem 2
Employee <- function(directory_name) {
  allEmails <- list.files(
    paste('../raw_data/enron_dataset/', directory_name, sep = ''),
    full.names = T, recursive = T
  ) %>% 
  str_sort(numeric = TRUE) %>% 
    # Sort file names in correct order (1 then 2, not 1 then 10)
  purrr::map(function(.filename) Email(.filename))
    # Map a list of emails
  
  thisEmployee <- list(
    name = from.Email(allEmails[[1]]),
    emails = allEmails
  )
  
  return(thisEmployee)
}

get_number_of_emails.Employee <- function(e) length(e$emails)
get_email_filename.Employee <- function(e, i) e$emails[[i]][3]
get_name.Employee <- function(e) e$name
```